nginx:
  image: "ldap_nginx"
  ports: 
    - 443:443
    - 80:80
  links:
    - registry:registry
  volumes:
    - ./nginx/certs/:/etc/ssl:ro
    - ./nginx/config/:/etc/nginx/:ro
  restart: always

registry:
  image: registry:2
  ports:
    - 127.0.0.1:5000:5000
  environment:
    REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
  volumes:
    - /mnt/nfs/docker/:/data
  restart: always
